# Generated by Django 4.0.5 on 2022-06-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=200)),
                ('codBarra', models.TextField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('precioCosto', models.TextField(max_length=200)),
                ('precioVenta', models.TextField(max_length=200)),
                ('marca', models.TextField(max_length=200)),
                ('categoria', models.TextField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
    ]
